### ISSUE TITLE
Support for `ipywidgets` 8

### ISSUE THREAD

**Issue by tilusnet** [voila-dashboards/voila#1188]
Hi,

When is `ipywidgets` 8.0+ compatibility planned for?

**Comment by edvard-bjarnason** [comment]
Hi, 

The problem now is that when you install in a clean environment you get ipywidgets 8 and then no widgets are rendered by volia :( and no clear error messages about what the problem is...

pip install voila
pip install jupyter
voila 
... and no widgets are rendered in notebooks

can be solved by:
pip install ipywidgets==7.7.2

**Comment by afonit** [comment]
https://github.com/voila-dashboards/voila/pull/1046

**Comment by tilusnet** [comment]
thanks @afonit

**Comment by martinRenou** [comment]
It's probable that this PR will get in instead https://github.com/voila-dashboards/voila/pull/846. It is turning Voila into a lab-based application and updating to ipywidgets 8.

**Comment by yasirroni** [comment]
I spent two days worth of time to debug and find the cause that voila stopped working in my side, and this is the reason!

Widgets did not appear because of Voila did not support `ipywidgets>8.0`!!!

Easy fix:

```
pip install ipywidgets<8.0
```
___
Lesson learned: better to pin all version in `requirements.txt` next time

**Comment by liamaharon** [comment]
If anyone has issues with `ipywidgets<8.0` try

```
pip install jupyterlab-widgets==1.1.1
```

the latest version of `jupyterlab-widgets` is not compatible with `ipywidgets<8.0`
