### ISSUE TITLE
Follow-up on #846 

### ISSUE THREAD

**Issue by trungleduc** [voila-dashboards/voila#1243]
Reposted from #846 

- [x] Depend on https://github.com/jupyter-server/jupyter_server_mathjax (https://github.com/voila-dashboards/voila/pull/846#pullrequestreview-649094759)
- [ ]  Load JupyterLab extensions from the CDN? Requires upstream feature for dynamic extensions?
- [x] Support JupyterLab themes, as an alternative or in addition to the theme and light themes from `nbconvert`: https://github.com/jupyter/nbconvert/blob/957c2e2476e1106fd4976af7d104c01cd5bb7562/setup.py#L52-L56
- [x] Fix the initial kernels / sessions request by providing mock managers: https://github.com/voila-dashboards/voila/pull/846#pullrequestreview-711440477

**Comment by jtpio** [comment]
We should also consider updating to the latest `@jupyterlab` packages and leverage the changes to `ServiceManager` as discussed in https://github.com/voila-dashboards/voila/pull/846#pullrequestreview-711440477.

Updating the top post to add this item.

**Comment by bollwyvl** [comment]
> Load JupyterLab extensions from the CDN?

**Please**, whatever happens, make CDN opt-in, providing a robust way to serve a known list of locally-available extensions, so that a they can be deployed along with a voila deployment. Reliance on (or having to co-deploy) a CDN is the cause of many issues when trying to actually own a non-public jupyter stack, and the well-understood scope and directory layout of prebuilt labextensions makes it far easier to manage than the previous requirejs mess.

To account for versioning, it might even be possible to serve directly from a pile of not-installed `.whl` or `.tar.bz2` packages, as the precise location of the assets would be known in advance. I'm not sure how notebooks would _advertise_ these versions, but this seems like an important, higher-order concern, and maybe not something `voila` can solve unilaterally.

> Support JupyterLab themes

Yes. Encouraging folk to author in a theme environment consistent with their deployment is huge.

**Comment by martinRenou** [comment]
Just adding a not that jupyterlab themes are actually already supported :D Though we don't support yet dynamically switching themes in the front-end.

**Comment by bollwyvl** [comment]
> dynamically switching themes in the front-end.

That's probably _good_ for most deployment use cases.

**Comment by trungleduc** [comment]
Closing as `Load JupyterLab extensions from the CDN? Requires upstream feature for dynamic extensions?` is not feasible in 0.5.0
