### ISSUE TITLE
voila selects the default python version instead of anaconda

### ISSUE THREAD

**Issue by argos0105** [voila-dashboards/voila#448]

**Comment by maartenbreddels** [comment]
Hi,

I don't think voila does anything specific here, we simply use the entry point system. An issue could be: After installation you need to deactivate/activate you env, or run hash -r / rehash for the shell to pick up binaries from your PATH

Closing this as I cannot imagine this being related to voila, if you believe otherwise, please leave a reproducible example so we can inspect it.

Regards,

Maarten
