### ISSUE TITLE
Update to Jupyter Client 7

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#941]
### Problem

Now that `jupyter_client` 7 is out, we should check whether we can bump the pin here:

https://github.com/voila-dashboards/voila/blob/487e4bf8ffb18672baa1b4f8e891a8c067bbade7/setup.py#L91

### Proposed Solution

Update the following line to allow `jupyter_client` 7, and see if tests still pass on CI:

https://github.com/voila-dashboards/voila/blob/487e4bf8ffb18672baa1b4f8e891a8c067bbade7/setup.py#L91

### Additional context

- Release notes: https://github.com/jupyter/jupyter_client/releases/tag/v7.0.0
- Migration Guide: https://jupyter-client.readthedocs.io/en/latest/migration.html

**Comment by ktaletsk** [comment]
Looks like the issue is not solved in the conda-forge package as of version `0.3.0-pyhd8ed1ab_0`. The dependency allowing jupyter_client 7 is not updated in conda.

This is the error I get when trying to install my conda environment
```
#24 180.9 Encountered problems while solving:
#24 180.9   - package voila-0.3.0-pyhd8ed1ab_0 requires jupyter_client >=6.1.3,<7, but none of the providers can be installed
```

You can verify the issue by downloading the the latest conda package (`noarch/voila-0.3.0-pyhd8ed1ab_0.tar.bz2`) from https://anaconda.org/conda-forge/voila/files and checking the contents of `info/index.json` file:
```
{
  "arch": null,
  "build": "pyhd8ed1ab_0",
  "build_number": 0,
  "depends": [
    "jupyter_client >=6.1.3,<7",
    "jupyter_server >=0.3.0,<2",
    "nbclient >=0.4.0,<0.6",
    "nbconvert >=6.0.0,<7",
    "python >=3.6",
    "websockets >=9"
  ],
  "license": "BSD-3-Clause",
  "license_family": "BSD",
  "name": "voila",
  "noarch": "python",
  "platform": null,
  "subdir": "noarch",
  "timestamp": 1639148161297,
  "version": "0.3.0"
}
```

I found no issues with pip install of the same version

**Comment by ktaletsk** [comment]
Actually, this is due to how conda manages dependencies vs PyPI. The dependencies section in conda feedstock must be in sync with the corresponding setup.cfg portion. They are out of sync now:

https://github.com/voila-dashboards/voila/blob/63a81d120f1c8b544e57f3292d5af89df11c71da/setup.cfg#L34-L39

https://github.com/conda-forge/voila-feedstock/blob/829928079ad61cc33cade1f18472da7aa0651afe/recipe/meta.yaml#L25-L31

I will open a PR to fix the feedstock, but maybe some automation could be set in place to keep them in sync
